export type Drink = {
  dateModified: string;
  idDrink: string;
  strAlcoholic: string;
  strCategory: string;
  strCreativeCommonsConfirmed: string;
  strDrink: string;
  strDrinkAlternate: any;
  strDrinkThumb: string;
  strGlass: string;
  strIBA: string;
  strImageAttribution: string;
  strImageSource: string;
  [key: `strIngredient${number}`]: string | null;
  strInstructions: string;
  strInstructionsDE: string;
  strInstructionsES: string;
  strInstructionsFR: string;
  strInstructionsIT: string;
  "strInstructionsZH-HANS": any;
  "strInstructionsZH-HANT": any;
  [key: `strMeasure${number}`]: string | null;
  strTags: string;
  strVideo: any;
};
